name: Sync Fork
on:
  # schedule:
    # - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!

jobs:
  fork-news:
    runs-on: ubuntu-latest
    name: Sync with parent repository
    steps:
      - id: fork-news-sync
        uses: vitornovictor/fork-news@v1.0.0
        with:
          from-branch: main
          from-repository: javiyt/tweetgram
          to-branch: main
          access-token: ${{ secrets.FORK_NEWS_TOKEN }}
