name: Sync Fork
on:
  # schedule:
    # - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: javiyt/tweetgram
          target_repository: quintodown/quintodownbot
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
