name: Sync Fork
on:
  # schedule:
    # - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!

jobs:
  fork-news:
    runs-on: ubuntu-latest
    name: Sync Fork
    steps:
      - id: update-fork
        uses: lelia/forker@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: tweetgram
          owner: javiyt
          org: quintodown
          user: javiyt
          addUser: true
